server:
  port: 5001

spring:
  application:
    name: USER_SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/lms_user_service
    username: postgres
    password: post
  jpa:
    hibernate:
      ddl-auto: update

